#------------------------------------------------------------------------
# To use this makefile the path for "$(FEAPPVHOME5_1)" must be set using
#   setenv FEAPPVHOME5_1=/....            (in .chrc or .tchrc)  or
#   export FEAPPVHOME5_1=/....            (in .bashrc or .bash_rc used)
# N.B. Information after the slash defines to FEAPPV directories.
#------------------------------------------------------------------------
#
# N.B. If a compiler option is used that sets ALL integers to be
#      integer*8, it is necessary to reset the parameter 'ipr = 1'
#      in file 'feappv.f' located in the 'main' directory.
#------------------------------------------------------------------------
# Location of feappv include files

  FINCLUDE = $(FEAPPVHOME5_1)/include

# Location of C-compiler include files (depends where compiler installed)

  CINCLUDE = /usr/X11R6/include -I$(FEAPPVHOME5_1)/include
# CINCLUDE = /opt/local/include -I$(FEAPPVHOME5_1)/include

#------------------------------------------------------------------------
# Which compilers to use (Set compiler names available on your computer)

  FF = gfortran
  CC = gcc

# FF = ifort                         # Intel compiler
# CC = icc                           # Intel compiler

#------------------------------------------------------------------------
# What optimization level to use

# Intel: ifort/icc compilers

# FFOPTFLAG = -O2 -Warn all
# CCOPTFLAG = -O2 -Wall

# Gnu: gfortran/gcc compilers

  FFOPTFLAG = -O3 -ftree-vectorize -Wall
  CCOPTFLAG = -O3 -ftree-vectorize -Wall

# FFOPTFLAG = -g -Wall
# CCOPTFLAG = -g -Wall

# FFOPTFLAG = -g -O3 -ftree-vectorize -Wall
# CCOPTFLAG = -g -O3 -ftree-vectorize -Wall

# FFOPTFLAG = -O2 -Wall
# CCOPTFLAG = -O2 -Wall

#------------------------------------------------------------------------
# Source Types (generally this is blank)

  FSOURCE = 
  CSOURCE = 
  F90SOURCE =

#------------------------------------------------------------------------
# Source Extender
  FEXT = f 
  CEXT = c

  F90EXT = f90

#------------------------------------------------------------------------
# Other options to be used by the compiler (generally this is blank)

  FOPTIONS =
  COPTIONS =

#------------------------------------------------------------------------
# What options to be used by the loader

# Intel

# LDOPTIONS = -L/opt/local/lib -mkl  -lX11 -lm

# gfortran

# LDOPTIONS = -L/opt/local/lib -lX11 -lm
  LDOPTIONS = -L/usr/X11R6/lib -lX11 -lm


#------------------------------------------------------------------------
# What archiving to use
  AR = ar rv

#------------------------------------------------------------------------
# Archive name

  ARFEAPPV = $(FEAPPVHOME5_1)/Feappv.a
#------------------------------------------------------------------------
