        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:12 2018
        MODULE PBEZLIN__genmod
          INTERFACE 
            SUBROUTINE PBEZLIN
            END SUBROUTINE PBEZLIN
          END INTERFACE 
        END MODULE PBEZLIN__genmod
