        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:13 2018
        MODULE PJSTRS__genmod
          INTERFACE 
            SUBROUTINE PJSTRS(TRIFL)
              LOGICAL(KIND=4) :: TRIFL
            END SUBROUTINE PJSTRS
          END INTERFACE 
        END MODULE PJSTRS__genmod
