        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:13 2018
        MODULE PLTNURB__genmod
          INTERFACE 
            SUBROUTINE PLTNURB(GMVOFF,NEW_PER)
              LOGICAL(KIND=4) :: GMVOFF
              LOGICAL(KIND=4) :: NEW_PER
            END SUBROUTINE PLTNURB
          END INTERFACE 
        END MODULE PLTNURB__genmod
