        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:07 2018
        MODULE PKNOTELM__genmod
          INTERFACE 
            SUBROUTINE PKNOTELM(KNOT,LENGTH,NELM)
              REAL(KIND=8) :: KNOT(*)
              INTEGER(KIND=4) :: LENGTH
              INTEGER(KIND=4) :: NELM
            END SUBROUTINE PKNOTELM
          END INTERFACE 
        END MODULE PKNOTELM__genmod
