        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:07 2018
        MODULE PKNOTLEN__genmod
          INTERFACE 
            SUBROUTINE PKNOTLEN(DKNOT,SKNOT,NKNOT)
              INTEGER(KIND=4) :: DKNOT
              INTEGER(KIND=4) :: SKNOT
              INTEGER(KIND=4) :: NKNOT
            END SUBROUTINE PKNOTLEN
          END INTERFACE 
        END MODULE PKNOTLEN__genmod
