        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:15 2018
        MODULE EXTRACTCONSTANT__genmod
          INTERFACE 
            SUBROUTINE EXTRACTCONSTANT(C_E,NELM)
              INTEGER(KIND=4) :: NELM
              REAL(KIND=8) :: C_E(1,1,NELM)
            END SUBROUTINE EXTRACTCONSTANT
          END INTERFACE 
        END MODULE EXTRACTCONSTANT__genmod
