        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:15 2018
        MODULE EXTRACTIDENTITY__genmod
          INTERFACE 
            SUBROUTINE EXTRACTIDENTITY(C_E,NELM)
              INTEGER(KIND=4) :: NELM
              REAL(KIND=8) :: C_E(2,2,NELM)
            END SUBROUTINE EXTRACTIDENTITY
          END INTERFACE 
        END MODULE EXTRACTIDENTITY__genmod
