        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:16 2018
        MODULE PEDGIN__genmod
          INTERFACE 
            SUBROUTINE PEDGIN
            END SUBROUTINE PEDGIN
          END INTERFACE 
        END MODULE PEDGIN__genmod
