        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:19 2018
        MODULE PNBLKLEN__genmod
          INTERFACE 
            SUBROUTINE PNBLKLEN(NBLOK,NBLKD)
              INTEGER(KIND=4) :: NBLOK
              INTEGER(KIND=4) :: NBLKD
            END SUBROUTINE PNBLKLEN
          END INTERFACE 
        END MODULE PNBLKLEN__genmod
