        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:20 2018
        MODULE PNPATLEN__genmod
          INTERFACE 
            SUBROUTINE PNPATLEN(DSID,NSID,NBLK)
              INTEGER(KIND=4) :: DSID
              INTEGER(KIND=4) :: NSID
              INTEGER(KIND=4) :: NBLK
            END SUBROUTINE PNPATLEN
          END INTERFACE 
        END MODULE PNPATLEN__genmod
