        !COMPILER-GENERATED INTERFACE MODULE: Fri May 25 07:34:20 2018
        MODULE PNSIDLEN__genmod
          INTERFACE 
            SUBROUTINE PNSIDLEN(DSID,NSID)
              INTEGER(KIND=4) :: DSID
              INTEGER(KIND=4) :: NSID
            END SUBROUTINE PNSIDLEN
          END INTERFACE 
        END MODULE PNSIDLEN__genmod
